# ADC executable twin -- Redfish mockup tree generator.
# Builds a DMTF-mockup-style /redfish/v1 resource tree (one folder per
# resource, index.json inside) from the ADC-SYS-001 registry. Serve it with
# serve-redfish.ps1. Zero dependencies; Windows PowerShell 5.1; ASCII only.

$ErrorActionPreference = 'Stop'
$base = Join-Path $PSScriptRoot '..\..'
$reg  = Join-Path $base 'registry'
$out  = Join-Path $base 'twin\redfish'

# --- registry constants ---
$node  = (Get-Content (Join-Path $reg 'interfaces\node-compute-electrical.json') -Raw) | ConvertFrom-Json
$hydro = (Get-Content (Join-Path $reg 'interfaces\cdu-tcs-hydraulic.json') -Raw) | ConvertFrom-Json
function PV($doc, $key) { ($doc.parameters | Where-Object { $_.key -eq $key }).value }
$pcsMW   = [double](PV $node 'bess_pcs_mw')        # 6
$flowGPM = [double](PV $hydro 'design_flow_gpm')   # 500
$flowLPM = [Math]::Round($flowGPM * 3.785411784, 1)
$rackLPM = [Math]::Round(31.25 * 3.785411784, 1)
$nRacks  = 16; $nGensets = 5

if (Test-Path $out) { Remove-Item $out -Recurse -Force -Confirm:$false }
function Res($rel, $obj) {
    $dir = Join-Path $out $rel
    New-Item -ItemType Directory -Force $dir | Out-Null
    $json = $obj | ConvertTo-Json -Depth 12
    [System.IO.File]::WriteAllText((Join-Path $dir 'index.json'), $json)
}
function OId($rel) { '/' + ($rel -replace '\\','/') }

# --- service root ---
Res 'redfish\v1' ([ordered]@{
    '@odata.id' = '/redfish/v1'; '@odata.type' = '#ServiceRoot.v1_17_0.ServiceRoot'
    Id = 'RootService'; Name = 'ADC Platform Twin Service Root'
    RedfishVersion = '1.24.0'
    Oem = @{ ADC = @{ Source = 'ADC-SYS-001 registry'; Note = 'Mockup generated by build-redfish-tree.ps1 -- POC Phase 1, simulated values at scenario baseline (t<0)' } }
    Chassis          = @{ '@odata.id' = '/redfish/v1/Chassis' }
    PowerEquipment   = @{ '@odata.id' = '/redfish/v1/PowerEquipment' }
    ThermalEquipment = @{ '@odata.id' = '/redfish/v1/ThermalEquipment' }
    Systems          = @{ '@odata.id' = '/redfish/v1/Systems' }
    Managers         = @{ '@odata.id' = '/redfish/v1/Managers' }
    TelemetryService = @{ '@odata.id' = '/redfish/v1/TelemetryService' }
    EventService     = @{ '@odata.id' = '/redfish/v1/EventService' }
})

# --- chassis collection ---
$chassisIds = @()
1..$nGensets | ForEach-Object { $chassisIds += "Genset-$_" }
$chassisIds += 'BESS-1'; $chassisIds += 'Switchgear-4kV'   # CDU is ThermalEquipment/CDUs/1, not a chassis member
1..$nRacks | ForEach-Object { $chassisIds += ('Rack-{0:D2}' -f $_) }
Res 'redfish\v1\Chassis' ([ordered]@{
    '@odata.id' = '/redfish/v1/Chassis'; '@odata.type' = '#ChassisCollection.ChassisCollection'
    Name = 'Chassis Collection'; 'Members@odata.count' = $chassisIds.Count
    Members = @($chassisIds | ForEach-Object { @{ '@odata.id' = "/redfish/v1/Chassis/$_" } })
})

# --- gensets (D1): 4 running at baseline 1.25 MW each, unit 5 = N+1 standby ---
1..$nGensets | ForEach-Object {
    $i = $_; $standby = ($i -eq 5)
    Res "redfish\v1\Chassis\Genset-$i" ([ordered]@{
        '@odata.id' = "/redfish/v1/Chassis/Genset-$i"; '@odata.type' = '#Chassis.v1_26_0.Chassis'
        Id = "Genset-$i"; Name = "Cat G3520H Genset $i"; ChassisType = 'Sidecar'
        Manufacturer = 'Caterpillar'; Model = 'G3520H'
        Status = @{ State = $(if ($standby) { 'StandbySpare' } else { 'Enabled' }); Health = 'OK' }
        PowerState = $(if ($standby) { 'Off' } else { 'On' })
        Sensors = @{ '@odata.id' = "/redfish/v1/Chassis/Genset-$i/Sensors" }
        Links = @{ ManagedBy = @(@{ '@odata.id' = "/redfish/v1/Managers/EMCP-$i" }) }
        Oem = @{ ADC = [ordered]@{
            Engine = [ordered]@{
                RatedContinuous_ekW = 2500; TerminalVoltage_kV = 4.16
                RunState = $(if ($standby) { 'Standby' } else { 'Running' })
                RunHours = $(if ($standby) { 118.5 } else { 1240.0 + 10 * $i }); StartCount = $(if ($standby) { 22 } else { 64 + $i })
                SpeedRPM = $(if ($standby) { 0 } else { 1800 }) }
            Aftertreatment = [ordered]@{
                Type = 'SCR + oxidation catalyst'; DEFLevelPercent = 78.0
                NOxOut_mgNm3 = $(if ($standby) { 0 } else { 38.0 }); CatalystBedTempCelsius = $(if ($standby) { 21.0 } else { 385.0 }) }
            Registry = 'system/registry/assets/microgrid-node.json' } }
    })
    # sensor collection per genset (PolyPhase pattern abbreviated to key sensors)
    Res "redfish\v1\Chassis\Genset-$i\Sensors" ([ordered]@{
        '@odata.id' = "/redfish/v1/Chassis/Genset-$i/Sensors"; '@odata.type' = '#SensorCollection.SensorCollection'
        Name = "Genset $i Sensors"; 'Members@odata.count' = 2
        Members = @(@{ '@odata.id' = "/redfish/v1/Chassis/Genset-$i/Sensors/Power" },
                    @{ '@odata.id' = "/redfish/v1/Chassis/Genset-$i/Sensors/Frequency" })
    })
    Res "redfish\v1\Chassis\Genset-$i\Sensors\Power" ([ordered]@{
        '@odata.id' = "/redfish/v1/Chassis/Genset-$i/Sensors/Power"; '@odata.type' = '#Sensor.v1_12_0.Sensor'
        Id = 'Power'; Name = "Genset $i Real Power"; ReadingType = 'Power'; ReadingUnits = 'W'
        Reading = $(if ($standby) { 0 } else { 1250000 })
        PeakIntervalReading = $(if ($standby) { 0 } else { 1262000 }); LowestIntervalReading = $(if ($standby) { 0 } else { 1241000 })
    })
    Res "redfish\v1\Chassis\Genset-$i\Sensors\Frequency" ([ordered]@{
        '@odata.id' = "/redfish/v1/Chassis/Genset-$i/Sensors/Frequency"; '@odata.type' = '#Sensor.v1_12_0.Sensor'
        Id = 'Frequency'; Name = "Genset $i Frequency"; ReadingType = 'Frequency'; ReadingUnits = 'Hz'
        Reading = $(if ($standby) { 0 } else { 60.0 }); LowestIntervalReading = $(if ($standby) { 0 } else { 59.98 })
    })
}

# --- BESS (D1): grid-forming, idle at baseline, SoC 85 ---
Res 'redfish\v1\Chassis\BESS-1' ([ordered]@{
    '@odata.id' = '/redfish/v1/Chassis/BESS-1'; '@odata.type' = '#Chassis.v1_26_0.Chassis'
    Id = 'BESS-1'; Name = "BESS $pcsMW MW PCS / 3 MWh LFP (grid-forming)"; ChassisType = 'Sidecar'
    Status = @{ State = 'Enabled'; Health = 'OK' }
    Sensors = @{ '@odata.id' = '/redfish/v1/Chassis/BESS-1/Sensors' }
    Oem = @{ ADC = [ordered]@{
        GridForming = [ordered]@{ Mode = 'GridForming'; VoltageReference_kV = 4.16; FrequencyReference_Hz = 60.0; DroopState = 'Forming' }
        Battery = [ordered]@{ StateOfChargePercent = 85.0; StateOfHealthPercent = 99.2; Chemistry = 'LFP'; UsableEnergy_MWh = 3.0; FireBasis = 'UL 9540A' }
        PCS = [ordered]@{ Rating_MW = $pcsMW; Quadrants = 4 }
        Registry = 'system/registry/interfaces/node-compute-electrical.json' } }
})
Res 'redfish\v1\Chassis\BESS-1\Sensors' ([ordered]@{
    '@odata.id' = '/redfish/v1/Chassis/BESS-1/Sensors'; '@odata.type' = '#SensorCollection.SensorCollection'
    Name = 'BESS Sensors'; 'Members@odata.count' = 2
    Members = @(@{ '@odata.id' = '/redfish/v1/Chassis/BESS-1/Sensors/RealPower' },
                @{ '@odata.id' = '/redfish/v1/Chassis/BESS-1/Sensors/StateOfCharge' })
})
Res 'redfish\v1\Chassis\BESS-1\Sensors\RealPower' ([ordered]@{
    '@odata.id' = '/redfish/v1/Chassis/BESS-1/Sensors/RealPower'; '@odata.type' = '#Sensor.v1_12_0.Sensor'
    Id = 'RealPower'; Name = 'BESS PCS Real Power (signed: + discharge / - charge)'
    ReadingType = 'Power'; ReadingUnits = 'W'; Reading = 0
    PeakIntervalReading = 5000000; LowestIntervalReading = -180000
    Oem = @{ ADC = @{ Note = 'Peak interval reflects the most recent coherent-step bridge event (5 MW design case)' } }
})
Res 'redfish\v1\Chassis\BESS-1\Sensors\StateOfCharge' ([ordered]@{
    '@odata.id' = '/redfish/v1/Chassis/BESS-1/Sensors/StateOfCharge'; '@odata.type' = '#Sensor.v1_12_0.Sensor'
    Id = 'StateOfCharge'; Name = 'BESS State of Charge'; ReadingType = 'Percent'; ReadingUnits = '%'; Reading = 85.0
})

# --- switchgear chassis + power distribution (D1) ---
Res 'redfish\v1\Chassis\Switchgear-4kV' ([ordered]@{
    '@odata.id' = '/redfish/v1/Chassis/Switchgear-4kV'; '@odata.type' = '#Chassis.v1_26_0.Chassis'
    Id = 'Switchgear-4kV'; Name = '4.16 kV Metal-Clad Paralleling Switchgear (5 kV class)'
    ChassisType = 'RackGroup'; Status = @{ State = 'Enabled'; Health = 'OK' }
    Links = @{ PowerDistribution = @(@{ '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV' }) }
})
Res 'redfish\v1\PowerEquipment' ([ordered]@{
    '@odata.id' = '/redfish/v1/PowerEquipment'; '@odata.type' = '#PowerEquipment.v1_2_0.PowerEquipment'
    Id = 'PowerEquipment'; Name = 'Power Equipment'
    PowerDistribution = @{ '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution' }
})
Res 'redfish\v1\PowerEquipment\PowerDistribution' ([ordered]@{
    '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution'; '@odata.type' = '#PowerDistributionCollection.PowerDistributionCollection'
    Name = 'Power Distribution Collection'; 'Members@odata.count' = 1
    Members = @(@{ '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV' })
})
Res 'redfish\v1\PowerEquipment\PowerDistribution\Bus-4kV' ([ordered]@{
    '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV'; '@odata.type' = '#PowerDistribution.v1_6_0.PowerDistribution'
    Id = 'Bus-4kV'; Name = '4.16 kV Paralleling Bus'; EquipmentType = 'Switchgear'
    Status = @{ State = 'Enabled'; Health = 'OK' }
    Circuits = @{ '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV/Circuits' }
    Redundancy = @(@{
        '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV#/Redundancy/0'
        '@odata.type' = '#Redundancy.v1_7_0.RedundantGroup'
        RedundancyType = 'NPlusM'; MinNumNeededForFaultTolerance = 4; MaxSupportedInGroup = 5
        Status = @{ State = 'Enabled'; Health = 'OK' }
        RedundancyGroup = @(1..$nGensets | ForEach-Object { @{ '@odata.id' = "/redfish/v1/Chassis/Genset-$_" } })
        Oem = @{ ADC = @{ Note = '10 MW firm = 4 running of 5; encoded per Redundancy v1.7.0 (MGN-TEL-001 sec 4.3)' } } })
})
$circuits = @()
1..$nGensets | ForEach-Object { $circuits += "Genset-$_-Feed" }
$circuits += 'BESS-1-Feed'; $circuits += 'StepUp-1'
Res 'redfish\v1\PowerEquipment\PowerDistribution\Bus-4kV\Circuits' ([ordered]@{
    '@odata.id' = '/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV/Circuits'; '@odata.type' = '#CircuitCollection.CircuitCollection'
    Name = 'Bus Circuits'; 'Members@odata.count' = $circuits.Count
    Members = @($circuits | ForEach-Object { @{ '@odata.id' = "/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV/Circuits/$_" } })
})
foreach ($c in $circuits) {
    $isStep = ($c -eq 'StepUp-1'); $isBess = ($c -eq 'BESS-1-Feed')
    Res "redfish\v1\PowerEquipment\PowerDistribution\Bus-4kV\Circuits\$c" ([ordered]@{
        '@odata.id' = "/redfish/v1/PowerEquipment/PowerDistribution/Bus-4kV/Circuits/$c"; '@odata.type' = '#Circuit.v1_9_0.Circuit'
        Id = $c; Name = $(if ($isStep) { 'Node step-up feeder 4.16 to 13.8/34.5 kV (ELEC-004 open)' } elseif ($isBess) { 'BESS PCS feed (4-quadrant)' } else { "$c breaker + sync" })
        CircuitType = 'Feeder'; NominalVoltage = 'AC4160V'; PhaseWiringType = 'ThreePhase4Wire'
        BreakerState = $(if ($c -eq 'Genset-5-Feed') { 'Off' } else { 'On' })
        Status = @{ State = 'Enabled'; Health = 'OK' }
    })
}

# --- ThermalEquipment / CDU (D3) ---
Res 'redfish\v1\ThermalEquipment' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment'; '@odata.type' = '#ThermalEquipment.v1_1_0.ThermalEquipment'
    Id = 'ThermalEquipment'; Name = 'Thermal Equipment'
    CDUs = @{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs' }
})
Res 'redfish\v1\ThermalEquipment\CDUs' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs'; '@odata.type' = '#CoolingUnitCollection.CoolingUnitCollection'
    Name = 'CDU Collection'; 'Members@odata.count' = 1
    Members = @(@{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1' })
})
Res 'redfish\v1\ThermalEquipment\CDUs\1' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1'; '@odata.type' = '#CoolingUnit.v1_5_0.CoolingUnit'
    Id = '1'; Name = 'ADC 2 MW CDU (Project Deschutes)'; EquipmentType = 'CDU'
    Manufacturer = 'ADC Solutions'; Model = 'ADC-CDU-DES-2MW'
    RatedFlowLitersPerMinute = $flowLPM
    Status = @{ State = 'Enabled'; Health = 'OK' }
    Pumps = @{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/Pumps' }
    PrimaryCoolantConnectors = @{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/PrimaryCoolantConnectors' }
    SecondaryCoolantConnectors = @{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/SecondaryCoolantConnectors' }
    LeakDetection = @{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/LeakDetection' }
    CoolingUnitRedundancy = @(@{
        '@odata.type' = '#Redundancy.v1_7_0.RedundantGroup'; RedundancyType = 'NPlusM'
        MinNumNeededForFaultTolerance = 1; MaxSupportedInGroup = 2
        RedundancyGroup = @(@{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/Pumps/1' }, @{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/Pumps/2' }) })
    Oem = @{ ADC = [ordered]@{
        ApproachTemperatureCelsius = 3.0; CoolantType = 'PG25'
        TCSInterface = [ordered]@{
            HeaderSupplyTemperatureCelsius = 30.0; HeaderReturnTemperatureCelsius = 35.0
            HeaderFlowLitersPerMinute = $flowLPM; RemoteEndOfLineDeltaPressurekPa = 41.4
            BranchCount = $nRacks * 2; Note = '170 kW DN50 branch cap at 6 fps -- registry tcs-rack-branch'
            WaterQuality = @{ pH = 8.1; ConductivityuScm = 1450; FilterDeltaPressurekPa = 12.0 } }
        SafetyAuthority = 'CDU PLC (CompactLogix 5380) -- never the telemetry plane'
        Registry = 'system/registry/assets/cdu.json' } }
})
Res 'redfish\v1\ThermalEquipment\CDUs\1\Pumps' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/Pumps'; '@odata.type' = '#PumpCollection.PumpCollection'
    Name = 'CDU Pumps (N+1)'; 'Members@odata.count' = 2
    Members = @(@{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/Pumps/1' }, @{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/Pumps/2' })
})
1..2 | ForEach-Object {
    $standby = ($_ -eq 2)
    Res "redfish\v1\ThermalEquipment\CDUs\1\Pumps\$_" ([ordered]@{
        '@odata.id' = "/redfish/v1/ThermalEquipment/CDUs/1/Pumps/$_"; '@odata.type' = '#Pump.v1_2_0.Pump'
        Id = "$_"; Name = "SPECK TOEMA065200 Pump $_"; PumpType = 'Liquid'
        Manufacturer = 'SPECK'; Model = 'TOEMA065200'
        Status = @{ State = $(if ($standby) { 'StandbySpare' } else { 'Enabled' }); Health = 'OK' }
        PumpSpeedPercent = @{ Reading = $(if ($standby) { 0 } else { 62.0 }) }
        SpeedControlPercent = @{ Reading = $(if ($standby) { 0 } else { 62.0 }); SetPoint = $(if ($standby) { 0 } else { 62.0 }); ControlMode = 'Automatic' }
        Oem = @{ ADC = @{ VFD = 'ABB ACH580-31-065A-4'; RatedFlowGPM = 500; RatedHead_psi = 112 } }
    })
}
Res 'redfish\v1\ThermalEquipment\CDUs\1\PrimaryCoolantConnectors' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/PrimaryCoolantConnectors'; '@odata.type' = '#CoolantConnectorCollection.CoolantConnectorCollection'
    Name = 'Primary (Facility) Coolant Connectors'; 'Members@odata.count' = 1
    Members = @(@{ '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/PrimaryCoolantConnectors/Facility' })
})
Res 'redfish\v1\ThermalEquipment\CDUs\1\PrimaryCoolantConnectors\Facility' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/PrimaryCoolantConnectors/Facility'; '@odata.type' = '#CoolantConnector.v1_2_0.CoolantConnector'
    Id = 'Facility'; Name = 'Facility PCW Loop'; CoolantConnectorType = 'Pair'
    SupplyTemperatureCelsius = @{ Reading = 27.0 }; ReturnTemperatureCelsius = @{ Reading = 33.5 }
    FlowLitersPerMinute = @{ Reading = $flowLPM }
    Oem = @{ ADC = @{ ControlValve = 'Belimo B6500'; ValvePositionPercent = 48.0; ValvePositionControlPercent = @{ SetPoint = 48.0; ControlMode = 'Automatic' } } }
})
$secMembers = @(1..$nRacks | ForEach-Object { @{ '@odata.id' = ('/redfish/v1/ThermalEquipment/CDUs/1/SecondaryCoolantConnectors/Rack-{0:D2}' -f $_) } })
Res 'redfish\v1\ThermalEquipment\CDUs\1\SecondaryCoolantConnectors' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/SecondaryCoolantConnectors'; '@odata.type' = '#CoolantConnectorCollection.CoolantConnectorCollection'
    Name = 'Secondary (TCS Rack Loop) Coolant Connectors'; 'Members@odata.count' = $nRacks
    Members = $secMembers
})
1..$nRacks | ForEach-Object {
    $r = ('Rack-{0:D2}' -f $_)
    Res "redfish\v1\ThermalEquipment\CDUs\1\SecondaryCoolantConnectors\$r" ([ordered]@{
        '@odata.id' = "/redfish/v1/ThermalEquipment/CDUs/1/SecondaryCoolantConnectors/$r"; '@odata.type' = '#CoolantConnector.v1_2_0.CoolantConnector'
        Id = $r; Name = "TCS Branch $r (DN50 supply + return)"; CoolantConnectorType = 'Pair'
        SupplyTemperatureCelsius = @{ Reading = 30.0 }; ReturnTemperatureCelsius = @{ Reading = 35.0 }
        FlowLitersPerMinute = @{ Reading = $rackLPM }; DeltaPressurekPa = @{ Reading = 64.8 }
        Oem = @{ ADC = @{ QD = 'Staubli RBE2 2in dry-break'; BalancingValvePositionPercent = 71.0; BranchCap_kW_at_6fps = 170 } }
    })
}
Res 'redfish\v1\ThermalEquipment\CDUs\1\LeakDetection' ([ordered]@{
    '@odata.id' = '/redfish/v1/ThermalEquipment/CDUs/1/LeakDetection'; '@odata.type' = '#LeakDetection.v1_1_0.LeakDetection'
    Id = 'LeakDetection'; Name = 'CDU + TCS Leak Detection'
    LeakDetectorGroups = @(1..3 | ForEach-Object { [ordered]@{
        GroupName = "Zone-$_"; HumidityPercent = $null
        Detectors = @(@{ DataSourceUri = ''; DeviceName = "Leak rope zone $_ (TraceTek/RLE)"; DetectorState = 'OK' })
        Oem = @{ ADC = @{ Voltage = 4.97; CurrentAmps = 0.012; Note = 'LeakDetector v1.6.0 V/I telemetry' } } } })
})

# --- Systems (D2, representative node) ---
Res 'redfish\v1\Systems' ([ordered]@{
    '@odata.id' = '/redfish/v1/Systems'; '@odata.type' = '#ComputerSystemCollection.ComputerSystemCollection'
    Name = 'Computer System Collection'; 'Members@odata.count' = 1
    Members = @(@{ '@odata.id' = '/redfish/v1/Systems/Node-01' })
})
Res 'redfish\v1\Systems\Node-01' ([ordered]@{
    '@odata.id' = '/redfish/v1/Systems/Node-01'; '@odata.type' = '#ComputerSystem.v1_25_0.ComputerSystem'
    Id = 'Node-01'; Name = 'Representative compute node (Rack-01)'; SystemType = 'Physical'
    Status = @{ State = 'Enabled'; Health = 'OK' }
    Links = @{ Chassis = @(@{ '@odata.id' = '/redfish/v1/Chassis/Rack-01' }) }
    Oem = @{ ADC = [ordered]@{
        GPUUtilizationPercent = 25.0; NodePower_kW = 62.5
        PowerLimit = @{ Active = $false; Note = 'Power-registry v1.3.0 chassis power-limit events subscribe via EventService' }
        Fabric = 'UALink (Port v1.18.0 / Processor v1.22.0)'
        BMCNote = 'BMC firmware family = OEM confirmation item (TEL-BMC); do not assume MegaRAC' } }
})

# --- rack chassis (D2 thermal envelope) ---
1..$nRacks | ForEach-Object {
    $r = ('Rack-{0:D2}' -f $_)
    Res "redfish\v1\Chassis\$r" ([ordered]@{
        '@odata.id' = "/redfish/v1/Chassis/$r"; '@odata.type' = '#Chassis.v1_26_0.Chassis'
        Id = $r; Name = "IT Rack $r (28in x 50in x 90.55in envelope)"; ChassisType = 'Rack'
        Status = @{ State = 'Enabled'; Health = 'OK' }
        Oem = @{ ADC = [ordered]@{
            PowerFeed = '4 feeds, 3+1 (4 makes 3), 90 kW/rack-spot'
            CoolantBranch = "/redfish/v1/ThermalEquipment/CDUs/1/SecondaryCoolantConnectors/$r"
            Registry = 'system/registry/assets/it-rack.json' } }
    })
}

# --- managers ---
$mgrs = @('EMCP-1','EMCP-2','EMCP-3','EMCP-4','EMCP-5','PLC-CDU-1','PlantMaster-1','BMC-Rack-01')
Res 'redfish\v1\Managers' ([ordered]@{
    '@odata.id' = '/redfish/v1/Managers'; '@odata.type' = '#ManagerCollection.ManagerCollection'
    Name = 'Manager Collection'; 'Members@odata.count' = $mgrs.Count
    Members = @($mgrs | ForEach-Object { @{ '@odata.id' = "/redfish/v1/Managers/$_" } })
})
foreach ($m in $mgrs) {
    $desc = switch -Wildcard ($m) {
        'EMCP-*'        { 'Cat EMCP 4.x genset controller (Layer 1 -- safety authority)' }
        'PLC-CDU-1'     { 'CompactLogix 5380 CDU PLC (Layer 1 -- safety authority)' }
        'PlantMaster-1' { 'Plant master / dispatch controller (CTRL-001 -> TEL-DISPATCH)' }
        default         { 'Rack BMC (native Redfish; firmware family TBD per TEL-BMC)' } }
    Res "redfish\v1\Managers\$m" ([ordered]@{
        '@odata.id' = "/redfish/v1/Managers/$m"; '@odata.type' = '#Manager.v1_21_0.Manager'
        Id = $m; Name = $desc; ManagerType = 'ManagementController'
        Status = @{ State = 'Enabled'; Health = 'OK' }
        Oem = @{ ADC = @{ AuthorityBoundary = 'Layer-1 retains deterministic control; this plane is supervisory only (MGN-TEL-001 sec 3.2/13)' } }
    })
}

# --- telemetry service: one report definition per cadence class ---
Res 'redfish\v1\TelemetryService' ([ordered]@{
    '@odata.id' = '/redfish/v1/TelemetryService'; '@odata.type' = '#TelemetryService.v1_4_0.TelemetryService'
    Id = 'TelemetryService'; Name = 'Telemetry Service'
    Status = @{ State = 'Enabled'; Health = 'OK' }
    MetricReportDefinitions = @{ '@odata.id' = '/redfish/v1/TelemetryService/MetricReportDefinitions' }
})
$defs = @(
    @{ id = 'ClassB-Supervisory'; period = 'PT1S';  what = 'GPU power/temp/util, BESS +-P and SoC, genset kW/V/Hz, CDU state, TCS branches; peak/dip interval capture enabled' },
    @{ id = 'ClassC-Contextual';  period = 'PT60S'; what = 'Weather/wet-bulb/dew-point, facility, emissions trend, fuel' },
    @{ id = 'ClassD-Compliance';  period = 'PT300S'; what = 'Run-hours, NOx/CO/CO2/HCHO, DEF, energy/demand -- mirrored to immutable historian (defends synthetic-minor permit)' })
Res 'redfish\v1\TelemetryService\MetricReportDefinitions' ([ordered]@{
    '@odata.id' = '/redfish/v1/TelemetryService/MetricReportDefinitions'; '@odata.type' = '#MetricReportDefinitionCollection.MetricReportDefinitionCollection'
    Name = 'Metric Report Definitions (cadence classes per MGN-TEL-001 sec 9)'; 'Members@odata.count' = $defs.Count
    Members = @($defs | ForEach-Object { @{ '@odata.id' = "/redfish/v1/TelemetryService/MetricReportDefinitions/$($_.id)" } })
})
foreach ($d in $defs) {
    Res "redfish\v1\TelemetryService\MetricReportDefinitions\$($d.id)" ([ordered]@{
        '@odata.id' = "/redfish/v1/TelemetryService/MetricReportDefinitions/$($d.id)"; '@odata.type' = '#MetricReportDefinition.v1_4_0.MetricReportDefinition'
        Id = $d.id; Name = $d.id; MetricReportDefinitionType = 'Periodic'
        Schedule = @{ RecurrenceInterval = $d.period }
        Oem = @{ ADC = @{ Contents = $d.what } }
    })
}
Res 'redfish\v1\EventService' ([ordered]@{
    '@odata.id' = '/redfish/v1/EventService'; '@odata.type' = '#EventService.v1_11_0.EventService'
    Id = 'EventService'; Name = 'Event Service'
    Status = @{ State = 'Enabled'; Health = 'OK' }
    Subscriptions = @{ '@odata.id' = '/redfish/v1/EventService/Subscriptions' }
    Oem = @{ ADC = @{ SubscribedRegistries = @('Environmental v1.5.0 (pair-reversal, dew-point)', 'Power v1.3.0 (chassis power-limit)', 'ManagerEvent v1.0.0', 'ResourceEvent v1.5.0') } }
})
Res 'redfish\v1\EventService\Subscriptions' ([ordered]@{
    '@odata.id' = '/redfish/v1/EventService/Subscriptions'; '@odata.type' = '#EventDestinationCollection.EventDestinationCollection'
    Name = 'Event Subscriptions'; 'Members@odata.count' = 1
    Members = @(@{ '@odata.id' = '/redfish/v1/EventService/Subscriptions/TelemetryOS' })
})
Res 'redfish\v1\EventService\Subscriptions\TelemetryOS' ([ordered]@{
    '@odata.id' = '/redfish/v1/EventService/Subscriptions/TelemetryOS'; '@odata.type' = '#EventDestination.v1_15_0.EventDestination'
    Id = 'TelemetryOS'; Name = 'ADC Telemetry OS event collector'
    Destination = 'https://telemetry-os.adc.local/redfish-events'   # mock endpoint, POC Phase 1
    SubscriptionType = 'RedfishEvent'; Protocol = 'Redfish'; EventFormatType = 'Event'
    DeliveryRetryPolicy = 'RetryForever'
    Status = @{ State = 'Enabled'; Health = 'OK' }
    Oem = @{ ADC = @{ MustDeliver = @('leak (LeakDetector)', 'redundancy-loss (Redundancy)', 'pair-reversal + dew-point (Environmental v1.5.0)', 'chassis power-limit (Power v1.3.0)', 'ManagerEvent', 'ResourceEvent') } }
})

$count = (Get-ChildItem $out -Recurse -Filter index.json).Count
Write-Output ("Generated {0} Redfish resources under {1}" -f $count, $out)
